import { NextResponse } from 'next/server'

/**
 * GET /api/transcript?videoId=XXXXXXXX&lang=ml
 *
 * Fetches YouTube captions using YouTube's internal player API endpoint.
 * This approach directly calls YouTube's /youtubei/v1/player API which
 * returns structured caption track data including the actual timedtext URLs.
 * 
 * No API key needed — uses the same internal API that the YouTube web player uses.
 */

interface CaptionTrack {
  baseUrl: string
  languageCode: string
  name?: { simpleText?: string }
  kind?: string // 'asr' = auto-generated
}

interface CaptionEvent {
  tStartMs: number
  dDurationMs?: number
  segs?: Array<{ utf8: string }>
}

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url)
  const videoId = searchParams.get('videoId')
  const lang = searchParams.get('lang') || 'ml'

  if (!videoId || videoId.length !== 11) {
    return NextResponse.json({ error: 'Invalid videoId' }, { status: 400 })
  }

  try {
    // Step 1: Call YouTube's internal player API to get caption track URLs
    const playerRes = await fetch(
      'https://www.youtube.com/youtubei/v1/player?key=AIzaSyAO_FJ2SlqU8Q4STEHLGCilw_Y9_11qcW8',
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120',
          'Accept-Language': 'en-US,en;q=0.9',
          'Origin': 'https://www.youtube.com',
          'Referer': `https://www.youtube.com/watch?v=${videoId}`,
          'X-YouTube-Client-Name': '1',
          'X-YouTube-Client-Version': '2.20231219.04.00',
        },
        body: JSON.stringify({
          context: {
            client: {
              clientName: 'WEB',
              clientVersion: '2.20231219.04.00',
              hl: 'en',
              gl: 'IN',
            },
          },
          videoId,
        }),
      }
    )

    if (!playerRes.ok) {
      throw new Error(`Player API returned ${playerRes.status}`)
    }

    const playerData = await playerRes.json()

    // Step 2: Extract caption tracks from the player response
    const captionTracks: CaptionTrack[] =
      playerData?.captions?.playerCaptionsTracklistRenderer?.captionTracks ?? []

    if (!captionTracks.length) {
      return NextResponse.json({
        captions: [],
        note: 'No captions available for this video. The channel owner needs to add subtitles in YouTube Studio.',
        videoId,
        availableLangs: [],
      })
    }

    // Step 3: Find best matching track — prefer requested lang, then auto-generated in any lang, then first available
    const findTrack = () => {
      // Exact match
      let t = captionTracks.find(t => t.languageCode === lang)
      if (t) return t
      // Auto-generated in requested lang
      t = captionTracks.find(t => t.languageCode === lang && t.kind === 'asr')
      if (t) return t
      // Auto-generated in any language (ASR)
      t = captionTracks.find(t => t.kind === 'asr')
      if (t) return t
      // English fallback
      t = captionTracks.find(t => t.languageCode === 'en')
      if (t) return t
      // First available
      return captionTracks[0]
    }

    const track = findTrack()

    // Step 4: Fetch the caption XML/JSON from the track's baseUrl
    const captionUrl = track.baseUrl + '&fmt=json3'
    const captionRes = await fetch(captionUrl, {
      headers: {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120',
        'Referer': `https://www.youtube.com/watch?v=${videoId}`,
      }
    })

    if (!captionRes.ok) {
      throw new Error(`Caption fetch returned ${captionRes.status}`)
    }

    const captionData = await captionRes.json()
    const events: CaptionEvent[] = captionData?.events ?? []

    // Step 5: Parse into clean { start, dur, text } segments
    const captions = events
      .filter((e) => e.segs && e.segs.length > 0)
      .map((e) => ({
        start: Math.round(e.tStartMs / 1000),
        dur: Math.round((e.dDurationMs ?? 2000) / 1000),
        text: e.segs!
          .map((s) => s.utf8)
          .join('')
          .replace(/\n/g, ' ')
          .trim()
      }))
      .filter((c) => c.text && c.text !== ' ')

    return NextResponse.json({
      captions,
      lang: track.languageCode,
      langName: track.name?.simpleText ?? track.languageCode,
      isAutoGenerated: track.kind === 'asr',
      videoId,
      availableLangs: captionTracks.map(t => ({
        code: t.languageCode,
        name: t.name?.simpleText ?? t.languageCode,
        auto: t.kind === 'asr',
      })),
    })

  } catch (error) {
    console.error('Transcript fetch error:', error)
    return NextResponse.json({
      captions: [],
      note: `Could not retrieve captions: ${error instanceof Error ? error.message : 'Unknown error'}`,
      videoId,
    }, { status: 200 }) // Return 200 so frontend handles gracefully
  }
}
